@startuml
class org.OpenHVACControl.ControllerService.TempsControllerService {
- {static} int zone1PrimaryTemp
- {static} int zone2PrimaryTemp
- {static} int zone3PrimaryTemp
- {static} int zone1SecondaryTemp
- {static} int zone2SecondaryTemp
- {static} int zone3SecondaryTemp
- {static} int zone1UsingTemp
- {static} int zone2UsingTemp
- {static} int zone3UsingTemp
+ {static} void setTemps(List<Zone>)
+ {static} List<Integer> getTemps()
}
class org.OpenHVACControl.HTMLControllers.TempsController {
+ List<Integer> getTemps()
}
class org.OpenHVACControl.hardware.GPIOControl {
+ GpioController gpio
}
class org.OpenHVACControl.MainController {
- {static} Pin ZONE_1_DAMPER_PIN
- {static} Pin ZONE_2_DAMPER_PIN
- {static} Pin ZONE_3_DAMPER_PIN
- {static} Pin W1_RELAY_PIN
- {static} Pin W2_RELAY_PIN
- {static} Pin Y1_RELAY_PIN
- {static} Pin Y2_RELAY_PIN
- {static} Pin FAN_RELAY_PIN
- CallsToSystem callsToSystem
- GPIOControl gpio
- List<Zone> zones
+ void mainController()
}
class org.OpenHVACControl.MainControllerUtils {
+ {static} List<Zone> getZonesRequestingHeat(List<Zone>)
+ {static} List<Request> getAllRequests(List<Zone>)
+ {static} Request totalRequests(List<Request>)
+ {static} boolean isCallingSecondStageHeat(List<Request>)
+ {static} boolean isCallingSecondStageCool(List<Request>)
+ {static} boolean getIsFanOnlyRequested(List<Request>)
+ {static} void updateFromFrontEnd(List<Integer>,List<String>,List<Boolean>,List<Zone>)
+ {static} List<Zone> initializeZones(Pin,Pin,Pin,GPIOControl)
+ {static} boolean validateZones(List<Zone>)
}
class org.OpenHVACControl.HTMLControllers.ZoneDataController {
+ List<String> getAliases()
+ List<String> getModes()
+ List<Boolean> getFansRequested()
+ void setMode(String,String)
+ void setFanRequested(String)
}
class org.OpenHVACControl.hardware.CallsToSystem {
- {static} int DAMPER_CLOSE_DELAY
- {static} Relay W1
- {static} Relay W2
- {static} Relay Y1
- {static} Relay Y2
- {static} Relay G
+ {static} List<Boolean> getRelayStates()
+ {static} Map<String,Boolean> getRelayStatesMap()
+ {static} SystemStates getSystemState()
+ {static} void turnHeatingOff(List<Zone>)
+ {static} void turnCoolingOff(List<Zone>)
+ {static} void turnFanOff(List<Zone>)
+ {static} void startStage1Heat(List<Zone>)
+ {static} void startStage2Heat()
+ {static} void turnOffStage2Heat()
+ {static} void startStage1Cool(List<Zone>)
+ {static} void startStage2Cool()
+ {static} void turnOffStage2Cool()
+ {static} void startFanOnly(List<Zone>)
}
class org.OpenHVACControl.HTMLControllers.SetpointsController {
+ List<Integer> getSetpoints()
+ int increaseSP(String)
+ int decreaseSP(String)
}
class org.OpenHVACControl.Sensors.InactiveZoneException {
}
class org.OpenHVACControl.HTMLControllers.WebPageController {
+ String getIndex()
+ String getSettings()
+ String getSensorsSetup()
}
class org.OpenHVACControl.Zones.Request {
- int heatingStages
- int coolingStages
- boolean fanRequest
- long timeStateStarted
+ int getHeatingStages()
+ void setHeatingStages(int)
+ int getCoolingStages()
+ void setCoolingStages(int)
+ boolean isFanRequested()
+ void setFanRequest(boolean)
+ long getTimeStateStarted()
+ void setTimeStateStarted(long)
+ String toString()
}
class org.OpenHVACControl.Zones.ZoneUtils {
~ {static} void getSensorData(TempSensor,TempSensor,HashMap<Zone.Temps,Integer>,boolean)
~ {static} void updateSetpoints(String,HashMap<Zone.Temps,Integer>)
~ {static} int getProcessSetpoint(Zone.Mode,HashMap<Zone.Temps,Integer>,boolean)
~ {static} int getCoolingStages(HashMap<Zone.Temps,Integer>,int,long,int)
~ {static} int getHeatingStages(HashMap<Zone.Temps,Integer>,int,long,int)
~ {static} int minutesElapsed(long)
}
class org.OpenHVACControl.ControllerService.OutputsControllerService {
- {static} boolean W1
- {static} boolean W2
- {static} boolean Y1
- {static} boolean Y2
- {static} boolean G
- {static} boolean damperZ1
- {static} boolean damperZ2
- {static} boolean damperZ3
+ {static} List<Boolean> getOutputs()
+ {static} void setOutputs(List<Boolean>,List<Zone>)
}
class org.OpenHVACControl.Sensors.InactiveSensorException {
}
class org.OpenHVACControl.hardware.Damper {
- Pin pin
- Relay relay
+ void setPinNumber(Pin)
+ boolean isOpen()
+ void open()
+ void close()
}
class org.OpenHVACControl.ControllerService.SetpointsControllerService {
- {static} int zone1OccupiedSP
- {static} int zone2OccupiedSP
- {static} int zone3OccupiedSP
- {static} int zone1UnoccupiedSP
- {static} int zone2UnoccupiedSP
- {static} int zone3UnoccupiedSP
+ {static} List<Integer> getSetpoints()
+ {static} Integer increaseSP(int)
+ {static} Integer decreaseSP(int)
}
class org.OpenHVACControl.HTMLControllers.OutputsController {
+ List<Boolean> getOutputs()
}
class org.OpenHVACControl.Sensors.TempSensor {
- long lastReadTime
- int lastTempRead
- TempSensor newSetupConfig
+ float getTemp()
# void applyNewConfig(AbstractSensor)
+ String toString()
}
abstract class org.OpenHVACControl.Sensors.AbstractSensor {
~ {static} String filePath
# String name
# String alias
# String address
# int sensorOffset
# GPIOControl gpio
# {abstract}void applyNewConfig(AbstractSensor)
+ void setName(String)
+ String getName()
+ void setAlias(String)
+ String getAlias()
+ void setAddress(String)
+ String getAddress()
+ int getSensorOffset()
+ void setSensorOffset(int)
+ String toString()
}
class org.OpenHVACControl.hardware.Relay {
- Pin pin
~ GPIOControl gpio
~ GpioPinDigitalOutput outputPin
~ boolean isActive
+ void setRelayOn()
+ void setRelayOff()
+ boolean getState()
}
class org.OpenHVACControl.HTMLControllers.SettingsController {
+ String getIP()
}
class org.OpenHVACControl.Main {
+ {static} void main(String[])
}
class org.OpenHVACControl.Zones.Zone {
~ {static} String filePath
- {static} Pin ZONE_1_DAMPER_PIN
- {static} Pin ZONE_2_DAMPER_PIN
- {static} Pin ZONE_3_DAMPER_PIN
- String name
- String alias
- TempSensor primaryTempSensor
- TempSensor secondaryTempSensor
- Mode mode
- HashMap<Temps,Integer> temps
- int secondaryIsPrimaryTime
- int secondStageTimeDelay
- int priority
- boolean isOccupied
- boolean damperIsOpen
- int outsideAirTemp
- boolean isActive
- boolean usingSecondarySensor
- long lastValidSensorRead
- Request request
- Damper damper
~ void deactivate()
+ Request getRequest()
+ {static} String getFilePath()
+ String getName()
+ void setName(String)
+ String getAlias()
+ void setAlias(String)
+ Mode getMode()
+ void setMode(Mode)
+ void setFanRequest(boolean)
+ boolean isFanRequested()
+ int getTemp(Temps)
+ void setTemp(Temps,int)
+ int getSecondaryIsPrimaryTime()
+ void setSecondaryIsPrimaryTime(int)
+ int getSecondStageTimeDelay()
+ void setSecondStageTimeDelay(int)
+ int getPriority()
+ void setPriority(int)
+ long getTimeStateStarted()
+ boolean isOccupied()
+ void setOccupied(boolean)
+ boolean isDamperIsOpen()
+ int getOutsideAirTemp()
+ void setOutsideAirTemp(int)
+ boolean isActive()
+ void setActive(boolean)
+ boolean isUsingSecondarySensor()
+ void setUsingSecondarySensor(boolean)
+ long getLastValidSensorRead()
+ void setLastValidSensorRead(long)
+ int getCurrentPrimaryTemp()
+ int getCurrentSecondaryTemp()
+ void openDamper()
+ void closeDamper()
+ int heatStagesRequested()
+ int coolStagesRequested()
+ String toString()
}
class org.OpenHVACControl.ControllerService.ZoneDataControllerService {
~ {static} List<String> aliases
~ {static} List<String> modes
~ {static} List<Boolean> fansRequested
+ {static} List<String> getAliases()
+ {static} List<String> getModes()
+ {static} List<Boolean> getFanRequests()
+ {static} void sendZoneDatatoFrontEnd(List<Zone>)
+ {static} void setMode(Integer,String)
+ {static} void setFanRequests(Integer)
}


org.OpenHVACControl.Sensors.Exception <|-- org.OpenHVACControl.Sensors.InactiveZoneException
org.OpenHVACControl.Sensors.Exception <|-- org.OpenHVACControl.Sensors.InactiveSensorException
org.OpenHVACControl.hardware.Thread <|-- org.OpenHVACControl.hardware.Damper
org.OpenHVACControl.Sensors.AbstractSensor <|-- org.OpenHVACControl.Sensors.TempSensor
@enduml